# Application
spring.application.name=Transfera

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Mail shared config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Actuator
management.endpoints.web.exposure.include=mappings,info,health,metrics,beans,env,loggers,threaddump

# Error & Logging
spring.web.error.include-message=always

# Default profile
spring.profiles.include=local
